/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicauca.figures.domain.presentation;

import com.unicauca.figures.domain.models.Circle;
import com.unicauca.figures.domain.models.Triangle;

/**
 *
 * @author JUAN DAVID
 */
public class GUITriangle extends javax.swing.JFrame {

    private Triangle triangle;

    /**
     * Creates new form GUITriangle
     */
    public GUITriangle() {
        initComponents();
        triangle = new Triangle(1, 2, 1, 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnCalcular = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlForm = new javax.swing.JPanel();
        lblBase = new javax.swing.JLabel();
        txtBase = new javax.swing.JTextField();
        lblAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        lblLadoIzq = new javax.swing.JLabel();
        txtLadoIzq = new javax.swing.JTextField();
        lblLadoDch = new javax.swing.JLabel();
        txtLadoDer = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();
        lblPerimetro = new javax.swing.JLabel();
        txtPerimetro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Sylfaen", 1, 36)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("TRIÁNGULO");
        getContentPane().add(lblTitle, java.awt.BorderLayout.PAGE_START);

        btnCalcular.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalcular.setName(""); // NOI18N
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCalcular);

        btnSalir.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSalir);

        getContentPane().add(pnlButtons, java.awt.BorderLayout.PAGE_END);

        pnlForm.setLayout(new java.awt.GridLayout(6, 2));

        lblBase.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblBase.setText("Base:");
        pnlForm.add(lblBase);

        txtBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaseActionPerformed(evt);
            }
        });
        pnlForm.add(txtBase);

        lblAltura.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblAltura.setText("Altura:");
        pnlForm.add(lblAltura);
        pnlForm.add(txtAltura);

        lblLadoIzq.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblLadoIzq.setText("Lado Izq:");
        pnlForm.add(lblLadoIzq);
        pnlForm.add(txtLadoIzq);

        lblLadoDch.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        lblLadoDch.setText("Lado Dch:");
        pnlForm.add(lblLadoDch);
        pnlForm.add(txtLadoDer);

        lblArea.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        lblArea.setText("Area:");
        pnlForm.add(lblArea);
        pnlForm.add(txtArea);

        lblPerimetro.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        lblPerimetro.setText("Perimetro:");
        pnlForm.add(lblPerimetro);
        pnlForm.add(txtPerimetro);

        getContentPane().add(pnlForm, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaseActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double base = Double.parseDouble(txtBase.getText());
        double altura = Double.parseDouble(txtAltura.getText());
        double ladoI = Double.parseDouble(txtLadoIzq.getText());
        double ladoD = Double.parseDouble(txtLadoDer.getText());

        triangle.setBase(base);
        triangle.setHeight(altura);
        triangle.setSideL(ladoI);
        triangle.setSideR(ladoD);

        txtArea.setText("Area: " + triangle.calculateArea());
        txtPerimetro.setText("Perimetro: " + triangle.calculatePerimeter());        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITriangle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITriangle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblBase;
    private javax.swing.JLabel lblLadoDch;
    private javax.swing.JLabel lblLadoIzq;
    private javax.swing.JLabel lblPerimetro;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtLadoDer;
    private javax.swing.JTextField txtLadoIzq;
    private javax.swing.JTextField txtPerimetro;
    // End of variables declaration//GEN-END:variables
}
